apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: zomboid-server
  namespace: zomboid
spec:
  resources:
    requests:
      ephemeral-storage: 8Gi
    limits:
      ephemeral-storage: 12Gi
  source:
    type: Git
    git:
      uri: https://github.com/Jacksonaustin/zomboid-server.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'zomboid-server:latest'
  triggers:
    - type: ConfigChange