apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zomboid-data
  namespace: zomboid
  labels:
    app: zomboid-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
